### ISSUE TITLE
Andrew is bad at github

### ISSUE THREAD

**Issue by myersan7** [cbahlai/Myers_monarchs#2]
I did those individual t-tests last week, but they don't seem to be showing up in the survival.r file in the repo. When I push from R it says it worked, but my changes don't seem to show up on the master version. Do you need to approve them or something?

**Comment by cbahlai** [comment]
It's not showing up anywhere on my end- and you should have permission! Looks like you were able to a direct file upload. Did you commit before you pushed?

**Comment by myersan7** [comment]
When I was hitting commit it gave me some kind of message about already
being committed. I have to stop by the lab in a couple hours, so I will try
again.
